// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncOqi322_loTirDuSnKep7dY43BOtf6k',
    appId: '1:221227976815:android:5d20a6e0f8bd54bcd5a59a',
    messagingSenderId: '221227976815',
    projectId: 'fitness-1ed30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-ZTzMdBAShW-D3QlVtmbzQuOxcpMKsQ',
    appId: '1:515747581143:android:76bfea24dfefaa8ef77492',
    messagingSenderId: '515747581143',
    projectId: 'woman-workout-fea97',
    storageBucket: 'woman-workout-fea97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyG1hstcBORoAfrKgQFrAqbJ-whSw44E',
    appId: '1:515747581143:ios:f2ea9f341525ef9ff77492',
    messagingSenderId: '515747581143',
    projectId: 'woman-workout-fea97',
    storageBucket: 'woman-workout-fea97.appspot.com',
    iosClientId:
        '515747581143-jac4n4113k9gvbspp97ksshpu826q6uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.workout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyG1hstcBORoAfrKgQFrAqbJ-whSw44E',
    appId: '1:515747581143:ios:f2ea9f341525ef9ff77492',
    messagingSenderId: '515747581143',
    projectId: 'woman-workout-fea97',
    storageBucket: 'woman-workout-fea97.appspot.com',
    iosClientId:
        '515747581143-jac4n4113k9gvbspp97ksshpu826q6uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.workout',
  );
}
